[dev]
  framework = "#static"

[build]
  functions = "functions"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.netlify/functions/webfinger"
  status = 200

[[redirects]]
  from = "/@*"
  to = "/.netlify/functions/account-redirect"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/account-redirect"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://syfaro.net/:splat"
  status = 301
